eureka:
  instance:
    prefer-ip-address: false
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : ${EUREKA_SERVER_ADDRESS:http://localhost:8762/}
