eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone : ${EUREKA_SERVER_ADDRESS:http://localhost:8762/eureka}

feign:
  httpclient:
    enabled: true
